title: Middlebury Well-Being
description: Find the opportunities, resources, and support to help you engage in your well-being at Middlebury.
baseurl: '/well-being'
suggestions_url: https://forms.middlebury.edu/offices/campuslife/well-being

markdown: kramdown
exclude:
  - node_modules
  - package.json
  - gulpfile.js
  - yarn.lock
  - README.md
  - '*.log'
